# Generated by Django 4.1.3 on 2022-11-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='moive_id',
            new_name='movie_id',
        ),
    ]
