# Generated by Django 4.1.3 on 2022-11-03 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_like',
            field=models.ManyToManyField(blank=True, related_name='like_movie', to='articles.comment'),
        ),
    ]
